// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/ratelimiter.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestIP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestIP) Reset() {
	*x = RequestIP{}
	mi := &file_proto_ratelimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestIP) ProtoMessage() {}

func (x *RequestIP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestIP.ProtoReflect.Descriptor instead.
func (*RequestIP) Descriptor() ([]byte, []int) {
	return file_proto_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *RequestIP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ResponseAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        bool                   `protobuf:"varint,1,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseAccess) Reset() {
	*x = ResponseAccess{}
	mi := &file_proto_ratelimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAccess) ProtoMessage() {}

func (x *ResponseAccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAccess.ProtoReflect.Descriptor instead.
func (*ResponseAccess) Descriptor() ([]byte, []int) {
	return file_proto_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAccess) GetAccess() bool {
	if x != nil {
		return x.Access
	}
	return false
}

var File_proto_ratelimiter_proto protoreflect.FileDescriptor

const file_proto_ratelimiter_proto_rawDesc = "" +
	"\n" +
	"\x17proto/ratelimiter.proto\x12\vratelimiter\"\x1b\n" +
	"\tRequestIP\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"(\n" +
	"\x0eResponseAccess\x12\x16\n" +
	"\x06access\x18\x01 \x01(\bR\x06access2Q\n" +
	"\vRateLimiter\x12B\n" +
	"\vCheckAccess\x12\x16.ratelimiter.RequestIP\x1a\x1b.ratelimiter.ResponseAccessB\x18Z\x16internal/delivery/grpcb\x06proto3"

var (
	file_proto_ratelimiter_proto_rawDescOnce sync.Once
	file_proto_ratelimiter_proto_rawDescData []byte
)

func file_proto_ratelimiter_proto_rawDescGZIP() []byte {
	file_proto_ratelimiter_proto_rawDescOnce.Do(func() {
		file_proto_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratelimiter_proto_rawDesc), len(file_proto_ratelimiter_proto_rawDesc)))
	})
	return file_proto_ratelimiter_proto_rawDescData
}

var file_proto_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ratelimiter_proto_goTypes = []any{
	(*RequestIP)(nil),      // 0: ratelimiter.RequestIP
	(*ResponseAccess)(nil), // 1: ratelimiter.ResponseAccess
}
var file_proto_ratelimiter_proto_depIdxs = []int32{
	0, // 0: ratelimiter.RateLimiter.CheckAccess:input_type -> ratelimiter.RequestIP
	1, // 1: ratelimiter.RateLimiter.CheckAccess:output_type -> ratelimiter.ResponseAccess
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ratelimiter_proto_init() }
func file_proto_ratelimiter_proto_init() {
	if File_proto_ratelimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratelimiter_proto_rawDesc), len(file_proto_ratelimiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratelimiter_proto_goTypes,
		DependencyIndexes: file_proto_ratelimiter_proto_depIdxs,
		MessageInfos:      file_proto_ratelimiter_proto_msgTypes,
	}.Build()
	File_proto_ratelimiter_proto = out.File
	file_proto_ratelimiter_proto_goTypes = nil
	file_proto_ratelimiter_proto_depIdxs = nil
}
