version: '3.8'

volumes:
  postgres_data:
  elastic_data:
  prometheus_data:
  grafana_data:

services:
  # Основное приложение FastAPI
  app:
    build: .
    container_name: bitpulse_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      #- elasticsearch
    command: /app/entrypoint.sh 
    
  # Воркер Celery (выполняет задачи)
  worker:
    build: .
    container_name: bitpulse_worker
    env_file: .env
    volumes:
      - .:/app
    command: celery -A fastapi_app.worker.celery_app worker --loglevel=info
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started
      app:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      

  # Планировщик Celery (отправляет задачи по расписанию)
  beat:
    build: .
    container_name: bitpulse_beat
    env_file: .env
    volumes:
      - .:/app
    command: celery -A fastapi_app.worker.celery_app beat --loglevel=info
    depends_on:
      - redis
      - postgres
      - app

  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: bitpulse_db
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis (Broker для Celery и Кеш)
  redis:
    image: redis:7-alpine
    container_name: bitpulse_redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: bitpulse_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # WARNING! Disable security for development only
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=warn
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status.*gold\\|green\\|yellow'"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  flower:
    image: mher/flower:2.0
    profiles: ["debug"]
    container_name: bitpulse_flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    profiles: ["debug"]
    container_name: bitpulse_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - I18N_LOCALE=ru-RU
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  test_db:
    image: postgres:15-alpine
    profiles: ["test"]
    container_name: bitpulse_test_db
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=bitpulse_test
    ports:
      - "${TEST_DB_PORT}:5432"

  prometheus:
    image: prom/prometheus:latest
    profiles: ["metrics"]
    container_name: bitpulse_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
    - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    profiles: ["metrics"]
    container_name: bitpulse_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: bitpulse_postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"
    profiles: ["metrics"]
    depends_on:
      - postgres

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: bitpulse_redis_exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    profiles: ["metrics"]
    depends_on:
      - redis