# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rate_limiter.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'rate_limiter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12rate_limiter.proto\x12\x0bratelimiter\"\x17\n\tRequestIP\x12\n\n\x02ip\x18\x01 \x01(\t\" \n\x0eResponseAccess\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x01 \x01(\x08\x32Q\n\x0bRateLimiter\x12\x42\n\x0b\x43heckAccess\x12\x16.ratelimiter.RequestIP\x1a\x1b.ratelimiter.ResponseAccessB\x18Z\x16internal/delivery/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rate_limiter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026internal/delivery/grpc'
  _globals['_REQUESTIP']._serialized_start=35
  _globals['_REQUESTIP']._serialized_end=58
  _globals['_RESPONSEACCESS']._serialized_start=60
  _globals['_RESPONSEACCESS']._serialized_end=92
  _globals['_RATELIMITER']._serialized_start=94
  _globals['_RATELIMITER']._serialized_end=175
# @@protoc_insertion_point(module_scope)
