"""create AlertModel with relationships

Revision ID: 0aa23471aef4
Revises: ba3dbd42aed9
Create Date: 2026-04-08 17:51:30.331788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa23471aef4'
down_revision: Union[str, Sequence[str], None] = 'ba3dbd42aed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('alert_type', sa.Enum('PRICE_THRESHOLD', name='alerttype'), nullable=False),
    sa.Column('alert_operator', sa.Enum('GT', 'GE', 'LT', 'LE', name='alertoperator'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
