"""add tg_chat_id field in UserModel

Revision ID: adafffce5e5c
Revises: 79c158abdb7a
Create Date: 2026-04-19 16:22:40.304657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adafffce5e5c'
down_revision: Union[str, Sequence[str], None] = '79c158abdb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_chat_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['tg_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'tg_chat_id')
    # ### end Alembic commands ###
