"""remove is_active and add alert_status

Revision ID: af7c58b0156d
Revises: d841132d0c76
Create Date: 2026-04-11 14:36:43.622259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7c58b0156d'
down_revision: Union[str, Sequence[str], None] = 'd841132d0c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('alert_type', sa.Enum('PRICE_THRESHOLD', name='alerttype'), nullable=False),
    sa.Column('alert_operator', sa.Enum('GT', 'GE', 'LT', 'LE', name='alertoperator'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('alert_status', sa.Enum('ACTIVE', 'TRIGGERED', 'INACTIVE', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
