"""add created_at and triggered_at fields in AlertModel

Revision ID: d841132d0c76
Revises: 0aa23471aef4
Create Date: 2026-04-09 15:50:42.238827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd841132d0c76'
down_revision: Union[str, Sequence[str], None] = '0aa23471aef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('alerts', sa.Column('triggered_at', sa.DateTime(), nullable=True))
    op.alter_column('alerts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('alerts', 'symbol')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('alerts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('alerts', 'triggered_at')
    op.drop_column('alerts', 'created_at')
    # ### end Alembic commands ###
