"""add index for user_id ticker_id in AlertModel

Revision ID: f9d536d5a62d
Revises: 4deb11a750b3
Create Date: 2026-05-09 10:18:48.301077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d536d5a62d'
down_revision: Union[str, Sequence[str], None] = '4deb11a750b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_ticker_id'), 'alerts', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_ticker_id'), table_name='alerts')
    # ### end Alembic commands ###
